org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric (https://fabricmc.net/develop)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

# Mod
mod_version=0.0.1
maven_group=dev.mcrt
archives_base_name=mcrt

# Native build: Debug | RelWithDebInfo | Release
native_build_type=RelWithDebInfo
